- hosts: remote
  become: yes

  vars_prompt:

    - name: packages
      prompt: "Quel package souhaitez-vous installer?"
      private: no

    - name: version
      prompt: "Dans quelle version? (latest par défaut)"
      private: no

  tasks:
    - name: install packages
      become_user: root
      vars:
        version: latest
      package:
        name:  "{{ packages }}"
        state: "{{ version }}"
