- hosts: remote
  vars:
    version: latest

  vars_prompt:

    - name: packages
      prompt: "Quel package souhaitez-vous installer?"
      private: no

    - name: version
      prompt: "Dans quelle version?"
      private: no

  tasks:
    - name: install packages
      become: yes
      package:
        name:  "{{ packages }}"
        state: "{{ version }}"
