---
# tasks file for server

# faire un update
# - name: Run the equivalent of "apt-get update" as a separate step
#   apt:
#     update_cache: yes
# cache_valid_time: 3600
# tags: update

# vérifier présence paquets pip
- name: test & installer paquets si nécessaire
  raw: test -e /usr/bin/setuptools || (pip install setuptools)
  #test -e /usr/bin/pip || (apt install -y pip) ; test -e /usr/bin/virtualenv || (apt install -y virtualenv) #; 

# installer le paquet souhaité
# - name: install packages
#   become_user: root
#   apt:
#     name:  "{{ packages }}"

# créer un user et ssh
# - name: "Create user accounts"
#   user:
#     name: "{{ user_name }}"
#     groups: users
#     append: yes
#     generate_ssh_key: yes
#     ssh_key_bits: 2048
#     ssh_key_file: .ssh/id_rsa
