---
# tasks file for server
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
- name: install packages
  become_user: root
  apt:
    name:  "{{ packages }}"