---
# tasks file for server

# faire un update
# - name: Run the equivalent of "apt-get update" as a separate step
#   apt:
#     update_cache: yes
# cache_valid_time: 3600
# tags: update


# installer le paquet souhaité
# - name: install packages
#   become_user: root
#   apt:
#     name:  "{{ packages }}"

# créer un user
- name: "Create user accounts"
  user:
    name:   "{{ user_name }}"
    groups: users
    append: yes
# SSH 
