---
# tasks file for server

# faire un update
# - name: Run the equivalent of "apt-get update" as a separate step
#   apt:
#     update_cache: yes
# cache_valid_time: 3600
# tags: update


# installer le paquet souhaité
# - name: install packages
#   become_user: root
#   apt:
#     name:  "{{ packages }}"

# créer un user
- name: "Create user accounts"
  user:
    name:   "{{ user_name }}"
    state: present
    groups: users
    append: yes
# SSH 
# - name: Create a 2048-bit SSH key for user
#   user:
#     name: "{{ user_name }}"
#     generate_ssh_key: yes
#     ssh_key_bits: 2048
#     ssh_key_file: .ssh/id_rsa
