---
# tasks file for server

# faire un update
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

# installer le paquet souhaité
- name: install packages
  become_user: root
  apt:
    name:  "{{ packages }}"

# créer un user
- name: "Create user accounts"
  user:
    name: "{{ user_name }}"

# SSH 
